sudo: false
dist: trusty

language: php

services:
  - elasticsearch
  - mysql

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  include:
    - php: 7.2
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.3
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
        - CODE_COVERAGE="--coverage-clover=coverage.clover"
        - PHPSTAN=true

before_install:
  - if [[ -z $CODE_COVERAGE ]]; then phpenv config-rm xdebug.ini ; fi
  - composer self-update

install:
  - phpenv config-add Tests/travis.php.ini
  - travis_retry composer update $COMPOSER_FLAGS
  - composer info -i
  - ./Tests/Application/console doctrine:database:create
  - ./Tests/Application/console doctrine:schema:create

script:
  - if [[ $PHPSTAN = true ]]; then ./vendor/bin/phpstan analyze .; fi
  - ./vendor/bin/phpunit $CODE_COVERAGE

after_script:
  - if [[ -n $CODE_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ -n $CODE_COVERAGE ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
